#include <DGLcommon/gl-headers.h>
#include <DGLcommon/gl-types.h>

typedef BOOL (WINAPI *PFNWGLCOPYCONTEXTPROC)(HGLRC, HGLRC, UINT);
typedef HGLRC (WINAPI *PFNWGLCREATECONTEXTPROC)(HDC);
typedef HGLRC (WINAPI *PFNWGLCREATELAYERCONTEXTPROC)(HDC, int);
typedef BOOL (WINAPI *PFNWGLDELETECONTEXTPROC)(HGLRC);
typedef HGLRC (WINAPI *PFNWGLGETCURRENTCONTEXTPROC)(VOID);
typedef HDC (WINAPI *PFNWGLGETCURRENTDCPROC)(VOID);
typedef PROC (WINAPI *PFNWGLGETPROCADDRESSPROC)(LPCSTR);
typedef BOOL (WINAPI *PFNWGLMAKECURRENTPROC)(HDC, HGLRC);
typedef BOOL (WINAPI *PFNWGLSHARELISTSPROC)(HGLRC, HGLRC);
typedef int  (WINAPI *PFNWGLCHOOSEPIXELFORMATPROC) (HDC a, CONST PIXELFORMATDESCRIPTOR *b);
typedef BOOL (WINAPI *PFNWGLDESCRIBELAYERPLANEPROC) (HDC a, int b, int c, UINT d, LPLAYERPLANEDESCRIPTOR e);
typedef int  (WINAPI *PFNWGLDESCRIBEPIXELFORMATPROC) (HDC a, int b, UINT c, LPPIXELFORMATDESCRIPTOR d);
typedef PROC (WINAPI *PFNWGLGETDEFAULTPROCADDRESSPROC) (LPCSTR a);
typedef int  (WINAPI *PFNWGLGETLAYERPALETTEENTRIESPROC) (HDC a, int b, int c, int d, COLORREF *e);
typedef int  (WINAPI *PFNWGLGETPIXELFORMATPROC) (HDC a);
typedef BOOL (WINAPI *PFNWGLREALIZELAYERPALETTEPROC) (HDC a, int b, BOOL c);
typedef int  (WINAPI *PFNWGLSETLAYERPALETTEENTRIESPROC) (HDC a, int b, int c, int d, CONST COLORREF *e);
typedef BOOL (WINAPI *PFNWGLSETPIXELFORMATPROC) (HDC a, int b, CONST PIXELFORMATDESCRIPTOR *c);
typedef BOOL (WINAPI *PFNWGLSWAPBUFFERSPROC) (HDC a);
typedef BOOL (WINAPI *PFNWGLSWAPLAYERBUFFERSPROC) (HDC a, UINT b);
typedef long (WINAPI *PFNWGLSWAPMULTIPLEBUFFERSPROC) (UINT, const WGLSWAP *);
typedef BOOL (WINAPI *PFNWGLUSEFONTBITMAPSAPROC) (HDC a, DWORD b, DWORD c, DWORD d);
typedef BOOL (WINAPI *PFNWGLUSEFONTBITMAPSWPROC) (HDC a, DWORD b, DWORD c, DWORD d);
typedef BOOL (WINAPI *PFNWGLUSEFONTOUTLINESAPROC) (HDC a, DWORD b, DWORD c, DWORD d, FLOAT e, FLOAT f, int g, LPGLYPHMETRICSFLOAT h);
typedef BOOL (WINAPI *PFNWGLUSEFONTOUTLINESWPROC) (HDC a, DWORD b, DWORD c, DWORD d, FLOAT e, FLOAT f, int g, LPGLYPHMETRICSFLOAT h);

#include "../../dump/codegen/nonExtTypedefs.inl"

#define POINTER_TYPE(X) X##_Type
#define FUNCTION_LIST_ELEMENT(name, type) typedef type POINTER_TYPE(name);
#include "../../dump/codegen/functionList.inl"
#undef FUNCTION_LIST_ELEMENT


#define POINTER(X) g_DirectPointers[X##_Call]
#define DIRECT_CALL(X) (*(POINTER_TYPE(X))POINTER(X))

extern void* g_DirectPointers[Entrypoints_NUM];