all: $(OUT)\QtGui4.dll $(OUT)\QtCore4.dll

$(OUT)\QtGui4.dll: $(QTDIR)\bin\QtGui4.dll
	copy $(QTDIR)\bin\QtGui4.dll $(OUT)\QtGui4.dll


$(OUT)\QtCore4.dll: $(QTDIR)\bin\QtCore4.dll
	copy $(QTDIR)\bin\QtCore4.dll $(OUT)\QtCore4.dll