
WINGDIAPI int  WINAPI wglChoosePixelFormat (HDC a, CONST PIXELFORMATDESCRIPTOR *b);
WINGDIAPI int  WINAPI wglDescribePixelFormat (HDC a, int b, UINT c, LPPIXELFORMATDESCRIPTOR d);
WINGDIAPI int  WINAPI wglGetPixelFormat (HDC a);
WINGDIAPI BOOL WINAPI wglSetPixelFormat (HDC a, int b, CONST PIXELFORMATDESCRIPTOR *c);