#!/bin/sh

xdg-mime uninstall debugler-mime.xml
xdg-desktop-menu uninstall debugler.desktop

xdg-icon-resource uninstall  --size 256 debugler
xdg-icon-resource uninstall  --size 48  debugler
xdg-icon-resource uninstall  --size 24  debugle

