#!/bin/sh

xdg-mime uninstall --mode system /usr/share/mime/packages/debugler-mime.xml
xdg-desktop-menu uninstall --mode system debugler.desktop

xdg-icon-resource uninstall --mode system  --size 256 debugler
xdg-icon-resource uninstall --mode system  --size 48  debugler
xdg-icon-resource uninstall --mode system  --size 24  debugle

