all: $(OUT)\Qt5Gui$(D).dll $(OUT)\Qt5Core$(D).dll $(OUT)\Qt5Xml$(D).dll

$(OUT)\Qt5Gui$(D).dll: $(QTDIR)\bin\Qt5Gui$(D).dll
	copy $(QTDIR)\bin\Qt5Gui$(D).dll $(OUT)\Qt5Gui$(D).dll


$(OUT)\Qt5Core$(D).dll: $(QTDIR)\bin\Qt5Core$(D).dll
	copy $(QTDIR)\bin\Qt5Core$(D).dll $(OUT)\Qt5Core$(D).dll
	
$(OUT)\Qt5Xml$(D).dll: $(QTDIR)\bin\Qt5Xml$(D).dll
	copy $(QTDIR)\bin\Qt5Xml$(D).dll $(OUT)\Qt5Xml$(D).dll