all: $(OUT)\QtGui$(D)4.dll $(OUT)\QtCore$(D)4.dll $(OUT)\QtXml$(D)4.dll

$(OUT)\QtGui$(D)4.dll: $(QTDIR)\bin\QtGui$(D)4.dll
	copy $(QTDIR)\bin\QtGui$(D)4.dll $(OUT)\QtGui$(D)4.dll


$(OUT)\QtCore$(D)4.dll: $(QTDIR)\bin\QtCore4.dll
	copy $(QTDIR)\bin\QtCore$(D)4.dll $(OUT)\QtCore$(D)4.dll
	
$(OUT)\QtXml$(D)4.dll: $(QTDIR)\bin\QtXml$(D)4.dll
	copy $(QTDIR)\bin\QtXml$(D)4.dll $(OUT)\QtXml$(D)4.dll